- name: Copy files from source to target
  synchronize: src={{ wp_dir_src }} dest={{ wp_dir_target }}
  delegate_to: {{ wp_host_src }}

- name: Backup DB
  local_action: mysql_db login_host={{ wp_mysql_src.host }} login_password={{ wp_mysql_src.passwd }} login_user={{ wp_mysql_src.user }} state=dump name={{ wp_mysql_src.db }} dest={{ wp_temp_dump }}

- name: Replace DB data
  replace: dst={{ wp_temp_dump }} regexp='{{ wp_domain_src }}' replace='{{ wp_domain_target }}'

- name: Import DB
  local_action: mysql_db login_host={{ wp_mysql_target.host }} login_password={{ wp_mysql_target.passwd }} login_user={{ wp_mysql_target.user }} state=dump name={{ wp_mysql_target.db }} dest={{ wp_temp_dump }}

- name: Upload wp-config
  template: src=wp-config.php.j2 dest={{ wp_dir_target }}/wp-config.php
  delegate_to: {{ wp_host_target }}
